name: stg_app
description: Standard Treatment Guidelines 2017.


publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  adaptive_theme: ^2.3.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  provider: ^6.0.0
  get: ^4.3.8
  sqflite: ^2.0.0+3
  expandable: ^5.0.1
  path_provider: ^2.0.0
  flutter_html: ^2.1.5
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner:

# dependency_overrides:
#   analyzer: 0.39.14

flutter:


  uses-material-design: true

 
  assets:
  #  - assets/html/
  #  - assets/json/
    - assets/images/coat_of_arms.png

  fonts:
    - family: Trebuc
      fonts:
        - asset: assets/fonts/trebuc.ttf
        - asset: assets/fonts/trebucbd.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

