name: stg_app
description: Standard Treatment Guidelines 2017.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  adaptive_theme: ^1.0.0
  share: ^0.6.5
  shared_preferences: ^0.5.10
  provider: ^4.3.2+2
  get: ^3.10.2
  sqflite: ^1.3.1+1
  expandable: ^4.1.4
  path_provider: ^1.6.14
  flutter_widget_from_html: ^0.5.0+3
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner:

# dependency_overrides:
#   analyzer: 0.39.14

flutter:


  uses-material-design: true

 
  # assets:
  #  - assets/html/
  #  - assets/json/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Trebuc
      fonts:
        - asset: assets/fonts/trebuc.ttf
        - asset: assets/fonts/trebucbd.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

